"""add group_holder_id field do group_posts table

Revision ID: 8b777e08329b
Revises: ffa5c82ac146
Create Date: 2024-03-25 02:35:50.750371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b777e08329b'
down_revision = 'ffa5c82ac146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_holder_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'group', ['group_holder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', mysql.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('post_id', ['post_id'], unique=True)
        batch_op.drop_column('group_holder_id')

    # ### end Alembic commands ###
