"""change user table

Revision ID: 94ea40795608
Revises: 43e732c972e1
Create Date: 2024-02-07 14:13:53.936063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ea40795608'
down_revision = '43e732c972e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_type', ['user_type'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_ibfk_1', 'user', ['user_type'], ['id'])

    # ### end Alembic commands ###
