"""Adding ryple table

Revision ID: 95d757451a69
Revises: ec52d7ca82ba
Create Date: 2024-02-13 01:33:46.713870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95d757451a69'
down_revision = 'ec52d7ca82ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comment', sa.String(length=240), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_ibfk_3', type_='foreignkey')
        batch_op.drop_column('reply_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key('comment_ibfk_3', 'comment', ['reply_id'], ['id'])

    op.drop_table('reply')
    # ### end Alembic commands ###
