"""update table post

Revision ID: abecba4223f2
Revises: ddaeae0ba6e2
Create Date: 2024-02-13 21:13:26.370016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abecba4223f2'
down_revision = 'ddaeae0ba6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=45), nullable=False))

    # ### end Alembic commands ###
